//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDataProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenDataProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cfc_splash_2 {
            get {
                object obj = ResourceManager.GetObject("cfc-splash-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;English&quot;: {
        ///        &quot;viewData&quot;: &quot;View Data&quot;,
        ///        &quot;filter&quot;: &quot;Filter&quot;,
        ///        &quot;sort&quot;: &quot;Sort&quot;,
        ///        &quot;chart&quot;: &quot;Chart&quot;,
        ///        &quot;map&quot;: &quot;Map&quot;,
        ///        &quot;changeLanguage&quot;: &quot;Change Language&quot;,
        ///        &quot;error&quot;: &quot;An error occurred while&quot;,
        ///        &quot;loaderTitle&quot;: &quot;Loader for Open Data Project v1.0&quot;,
        ///        &quot;queryPickerTitle&quot;: &quot;Pick a query&quot;,
        ///        &quot;other&quot;: &quot;Other&quot;,
        ///        &quot;language&quot;: &quot;Language&quot;,
        ///        &quot;help&quot;: &quot;Help&quot;,
        ///        &quot;about&quot;: &quot;About&quot;,
        ///        &quot;tools&quot;: &quot;Tools&quot;,
        ///        &quot;use&quot;: &quot;U [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vocab {
            get {
                return ResourceManager.GetString("vocab", resourceCulture);
            }
        }
    }
}
